export const OBTENER_PRODUCTOS="OBTENER_PRODUCTOS";
export const OBTENER_PRODUCTO="OBTENER_PRODUCTO";

export const OBTENER_USUARIO="OBTENER_USUARIO"
export const OBTENER_USUARIO_DEFAULT="OBTENER_USUARIO_DEFAULT"
export const OBTENER_DIRECCIONES="OBTNER_DIRECCIONES"
export const OBTENER_DIRECCION="OBTNER_DIRECCION"
export const DIRECCION_RESET="DIRECION_RESET"
export const AGREGAR_DIRECCIONES="AGREGAR_DIRECCIONES"
export const BORRAR_DIRECION="BORRAR_DIRECCION"
export const MODIFICAR_DIRECCION="MODIFICAR_DIRECCION"
export const LOGIN="LOGIN"
export const LOGOUT="LOGOUT"
export const LOGIN_ERROR="LOGIN_ERROR"
export const MODIFICAR_USUARIO="MODIFICAR_USUARIO"

export const OCULTAR_ERROR='OCULTAR_ERROR'
export const REQUEST='REQUEST'
export const ERROR_HANDLER='ERROR_HANLDER'

export const OBTENER_CARRITO='OBTENER_CARRITO'
export const CREAR_CARRITO='CREAR_CARRITO'
export const ERROR_OBTENER_CARRITO='ERROR_OBTENER_CARRITO'
export const AGREGAR_ITEM_CARRITO='AGREGAR_ITEM_CARRITO'
export const BORRAR_ITEM_CARRITO='BORRAR_ITEM_CARRITO'
